// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: auth.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from auth.proto</summary>
public static partial class AuthReflection {

  #region Descriptor
  /// <summary>File descriptor for auth.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AuthReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgphdXRoLnByb3RvIlgKEGMyYV9yZWdpc3Rlcl9yZXESEAoIdXNlcm5hbWUY",
          "ASABKAkSCQoBcxgCIAEoCRIJCgF2GAMgASgJEg0KBWVtYWlsGAQgASgJEg0K",
          "BXBob25lGAUgASgJIjQKEGEyY19yZWdpc3Rlcl9yZXASIAoGcmVzdWx0GAEg",
          "ASgOMhAuQWNjb3VudE9wUmVzdWx0IicKE2MyYV9sb2dvbl9jaGFsbGVuZ2US",
          "EAoIdXNlcm5hbWUYASABKAkiLgoNYTJjX2xvZ29uX2FzaxISCgpwdWJsaWNf",
          "a2V5GAEgASgJEgkKAXMYAiABKAkiKAoPYzJhX2xvZ29uX3Byb29mEgkKAUEY",
          "ASABKAkSCgoCTTEYAiABKAkisAEKDWEyY19sb2dvbl9yZXASIAoGcmVzdWx0",
          "GAEgASgOMhAuQWNjb3VudE9wUmVzdWx0EhAKCHVzZXJuYW1lGAIgASgJEhIK",
          "CmFjY291bnRfaWQYAyABKA0SDAoEZ3VpZBgEIAEoDRIQCghzZGtfY29kZRgF",
          "IAEoBRILCgNhZ2UYBiABKAUSFQoNaXNfaWRlbnRpZmllZBgHIAEoCBITCgt1",
          "bmxvY2tfdGltZRgIIAEoAyJCChBhMmNfbG9nb25fcmVnaW9uEgoKAmlwGAEg",
          "ASgJEgwKBHBvcnQYAiABKA0SFAoMaHR0cF9hZGRyZXNzGAMgASgJInkKDWMy",
          "YV9sb2dvbl9zZGsSDwoHb3Blbl9pZBgBIAEoCRIOCgZhcHBfaWQYAiABKAkS",
          "DgoGY2NoX2lkGAMgASgJEhQKDGFjY2Vzc190b2tlbhgEIAEoCRIPCgdhcHBf",
          "a2V5GAUgASgJEhAKCHNka190eXBlGAYgASgJIkIKD2MyYV9sb2dvbl9hcHBs",
          "ZRIXCg91c2VyX2lkZW50aWZpZXIYASABKAkSFgoOaWRlbnRpdHlfdG9rZW4Y",
          "AiABKAkiNwoQYzJhX2xvZ29uX2dvb2dsZRIRCglnb29nbGVfaWQYASABKAkS",
          "EAoIaWRfdG9rZW4YAiABKAkiIwoPYzJhX2xvZ29uX3N1cGVyEhAKCHVzZXJu",
          "YW1lGAIgASgJIjUKGmMyYV9sb2dvbl9hcHBsZV9nYW1lY2VudGVyEhcKD3Vz",
          "ZXJfaWRlbnRpZmllchgBIAEoCSqNAgoPQWNjb3VudE9wUmVzdWx0EgwKCEFP",
          "Ul9OVUxMEAASCgoGQU9SX09LEAESFQoRQU9SX05BTUVfVE9PX0xPTkcQAhIZ",
          "ChVBT1JfUEFTU19XUk9OR19MRU5HVEgQAxIaChZBT1JfTkFNRV9BTFJFQURZ",
          "X0VYSVNUEAQSFgoSQU9SX05BTUVfTk9UX0VYSVNUEAUSGQoVQU9SX0RCX0lO",
          "VEVSTkFMX0VSUk9SEAYSGAoUQU9SX1BBU1NfV1JPTkdfRVJST1IQBxIUChBB",
          "T1JfSURfT1VUX1JBTkdFEAgSFgoSQU9SX0FDQ09VTlRfTE9DS0VEEAkSFwoT",
          "QU9SX1NWQ19NQUlOVEVOQU5DRRAKKqsDCglBdXRoTXNnSUQSEQoNQVVUSF9N",
          "U0dfTlVMTBAAEh8KGUFVVEhfTVNHX0MyQV9SRUdJU1RFUl9SRVEQydwDEh8K",
          "GUFVVEhfTVNHX0EyQ19SRUdJU1RFUl9SRVAQytwDEiIKHEFVVEhfTVNHX0My",
          "QV9MT0dPTl9DSEFMTEVOR0UQseQDEhwKFkFVVEhfTVNHX0EyQ19MT0dPTl9B",
          "U0sQsuQDEh4KGEFVVEhfTVNHX0MyQV9MT0dPTl9QUk9PRhCz5AMSHAoWQVVU",
          "SF9NU0dfQTJDX0xPR09OX1JFUBC05AMSHwoZQVVUSF9NU0dfQTJDX0xPR09O",
          "X1JFR0lPThC15AMSHAoWQVVUSF9NU0dfQzJBX0xPR09OX1NESxC25AMSHgoY",
          "QVVUSF9NU0dfQzJBX0xPR09OX1NVUEVSELjkAxIeChhBVVRIX01TR19DMkFf",
          "TE9HT05fQVBQTEUQuuQDEikKI0FVVEhfTVNHX0MyQV9MT0dPTl9BUFBMRV9H",
          "QU1FQ0VOVEVSELvkAxIfChlBVVRIX01TR19DMkFfTE9HT05fR09PR0xFELzk",
          "A2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AccountOpResult), typeof(global::AuthMsgID), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::c2a_register_req), global::c2a_register_req.Parser, new[]{ "Username", "S", "V", "Email", "Phone" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::a2c_register_rep), global::a2c_register_rep.Parser, new[]{ "Result" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::c2a_logon_challenge), global::c2a_logon_challenge.Parser, new[]{ "Username" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::a2c_logon_ask), global::a2c_logon_ask.Parser, new[]{ "PublicKey", "S" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::c2a_logon_proof), global::c2a_logon_proof.Parser, new[]{ "A", "M1" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::a2c_logon_rep), global::a2c_logon_rep.Parser, new[]{ "Result", "Username", "AccountId", "Guid", "SdkCode", "Age", "IsIdentified", "UnlockTime" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::a2c_logon_region), global::a2c_logon_region.Parser, new[]{ "Ip", "Port", "HttpAddress" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::c2a_logon_sdk), global::c2a_logon_sdk.Parser, new[]{ "OpenId", "AppId", "CchId", "AccessToken", "AppKey", "SdkType" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::c2a_logon_apple), global::c2a_logon_apple.Parser, new[]{ "UserIdentifier", "IdentityToken" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::c2a_logon_google), global::c2a_logon_google.Parser, new[]{ "GoogleId", "IdToken" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::c2a_logon_super), global::c2a_logon_super.Parser, new[]{ "Username" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::c2a_logon_apple_gamecenter), global::c2a_logon_apple_gamecenter.Parser, new[]{ "UserIdentifier" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// 账号操作结果
/// </summary>
public enum AccountOpResult {
  [pbr::OriginalName("AOR_NULL")] AorNull = 0,
  /// <summary>
  /// 成功
  /// </summary>
  [pbr::OriginalName("AOR_OK")] AorOk = 1,
  /// <summary>
  /// 名字太长
  /// </summary>
  [pbr::OriginalName("AOR_NAME_TOO_LONG")] AorNameTooLong = 2,
  /// <summary>
  /// 密码长度异常
  /// </summary>
  [pbr::OriginalName("AOR_PASS_WRONG_LENGTH")] AorPassWrongLength = 3,
  /// <summary>
  /// 名字已存在
  /// </summary>
  [pbr::OriginalName("AOR_NAME_ALREADY_EXIST")] AorNameAlreadyExist = 4,
  /// <summary>
  /// 名字不存在
  /// </summary>
  [pbr::OriginalName("AOR_NAME_NOT_EXIST")] AorNameNotExist = 5,
  /// <summary>
  /// 数据库内部错误
  /// </summary>
  [pbr::OriginalName("AOR_DB_INTERNAL_ERROR")] AorDbInternalError = 6,
  /// <summary>
  /// 密码错误
  /// </summary>
  [pbr::OriginalName("AOR_PASS_WRONG_ERROR")] AorPassWrongError = 7,
  /// <summary>
  /// id范围越界
  /// </summary>
  [pbr::OriginalName("AOR_ID_OUT_RANGE")] AorIdOutRange = 8,
  /// <summary>
  /// 账号被锁
  /// </summary>
  [pbr::OriginalName("AOR_ACCOUNT_LOCKED")] AorAccountLocked = 9,
  /// <summary>
  /// 服务维护中
  /// </summary>
  [pbr::OriginalName("AOR_SVC_MAINTENANCE")] AorSvcMaintenance = 10,
}

/// <summary>
/// 消息ID
/// </summary>
public enum AuthMsgID {
  /// <summary>
  /// 禁用
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_NULL")] AuthMsgNull = 0,
  /// <summary>
  /// 注册请求
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_C2A_REGISTER_REQ")] AuthMsgC2ARegisterReq = 61001,
  /// <summary>
  /// 注册返回
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_A2C_REGISTER_REP")] AuthMsgA2CRegisterRep = 61002,
  /// <summary>
  /// 登录请求
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_C2A_LOGON_CHALLENGE")] AuthMsgC2ALogonChallenge = 62001,
  /// <summary>
  /// 登录询问
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_A2C_LOGON_ASK")] AuthMsgA2CLogonAsk = 62002,
  /// <summary>
  /// 登录凭据
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_C2A_LOGON_PROOF")] AuthMsgC2ALogonProof = 62003,
  /// <summary>
  /// 登录结果
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_A2C_LOGON_REP")] AuthMsgA2CLogonRep = 62004,
  /// <summary>
  /// 登录Logic信息
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_A2C_LOGON_REGION")] AuthMsgA2CLogonRegion = 62005,
  /// <summary>
  /// SDK登录
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_C2A_LOGON_SDK")] AuthMsgC2ALogonSdk = 62006,
  /// <summary>
  /// 无密码登录
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_C2A_LOGON_SUPER")] AuthMsgC2ALogonSuper = 62008,
  /// <summary>
  /// Apple登录
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_C2A_LOGON_APPLE")] AuthMsgC2ALogonApple = 62010,
  /// <summary>
  /// Apple GameCenter登录
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_C2A_LOGON_APPLE_GAMECENTER")] AuthMsgC2ALogonAppleGamecenter = 62011,
  /// <summary>
  /// GooglePlay登录
  /// </summary>
  [pbr::OriginalName("AUTH_MSG_C2A_LOGON_GOOGLE")] AuthMsgC2ALogonGoogle = 62012,
}

#endregion

#region Messages
public sealed partial class c2a_register_req : pb::IMessage<c2a_register_req> {
  private static readonly pb::MessageParser<c2a_register_req> _parser = new pb::MessageParser<c2a_register_req>(() => new c2a_register_req());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<c2a_register_req> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_register_req() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_register_req(c2a_register_req other) : this() {
    username_ = other.username_;
    s_ = other.s_;
    v_ = other.v_;
    email_ = other.email_;
    phone_ = other.phone_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_register_req Clone() {
    return new c2a_register_req(this);
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 1;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "s" field.</summary>
  public const int SFieldNumber = 2;
  private string s_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string S {
    get { return s_; }
    set {
      s_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "v" field.</summary>
  public const int VFieldNumber = 3;
  private string v_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string V {
    get { return v_; }
    set {
      v_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "email" field.</summary>
  public const int EmailFieldNumber = 4;
  private string email_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Email {
    get { return email_; }
    set {
      email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "phone" field.</summary>
  public const int PhoneFieldNumber = 5;
  private string phone_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Phone {
    get { return phone_; }
    set {
      phone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as c2a_register_req);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(c2a_register_req other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Username != other.Username) return false;
    if (S != other.S) return false;
    if (V != other.V) return false;
    if (Email != other.Email) return false;
    if (Phone != other.Phone) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (S.Length != 0) hash ^= S.GetHashCode();
    if (V.Length != 0) hash ^= V.GetHashCode();
    if (Email.Length != 0) hash ^= Email.GetHashCode();
    if (Phone.Length != 0) hash ^= Phone.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Username.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Username);
    }
    if (S.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(S);
    }
    if (V.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(V);
    }
    if (Email.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Email);
    }
    if (Phone.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Phone);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (S.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(S);
    }
    if (V.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(V);
    }
    if (Email.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
    }
    if (Phone.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Phone);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(c2a_register_req other) {
    if (other == null) {
      return;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.S.Length != 0) {
      S = other.S;
    }
    if (other.V.Length != 0) {
      V = other.V;
    }
    if (other.Email.Length != 0) {
      Email = other.Email;
    }
    if (other.Phone.Length != 0) {
      Phone = other.Phone;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Username = input.ReadString();
          break;
        }
        case 18: {
          S = input.ReadString();
          break;
        }
        case 26: {
          V = input.ReadString();
          break;
        }
        case 34: {
          Email = input.ReadString();
          break;
        }
        case 42: {
          Phone = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class a2c_register_rep : pb::IMessage<a2c_register_rep> {
  private static readonly pb::MessageParser<a2c_register_rep> _parser = new pb::MessageParser<a2c_register_rep>(() => new a2c_register_rep());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<a2c_register_rep> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_register_rep() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_register_rep(a2c_register_rep other) : this() {
    result_ = other.result_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_register_rep Clone() {
    return new a2c_register_rep(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::AccountOpResult result_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::AccountOpResult Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as a2c_register_rep);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(a2c_register_rep other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Result != other.Result) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Result != 0) hash ^= Result.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Result != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Result);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Result != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(a2c_register_rep other) {
    if (other == null) {
      return;
    }
    if (other.Result != 0) {
      Result = other.Result;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          result_ = (global::AccountOpResult) input.ReadEnum();
          break;
        }
      }
    }
  }

}

public sealed partial class c2a_logon_challenge : pb::IMessage<c2a_logon_challenge> {
  private static readonly pb::MessageParser<c2a_logon_challenge> _parser = new pb::MessageParser<c2a_logon_challenge>(() => new c2a_logon_challenge());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<c2a_logon_challenge> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_challenge() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_challenge(c2a_logon_challenge other) : this() {
    username_ = other.username_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_challenge Clone() {
    return new c2a_logon_challenge(this);
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 1;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as c2a_logon_challenge);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(c2a_logon_challenge other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Username != other.Username) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Username.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Username);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(c2a_logon_challenge other) {
    if (other == null) {
      return;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Username = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class a2c_logon_ask : pb::IMessage<a2c_logon_ask> {
  private static readonly pb::MessageParser<a2c_logon_ask> _parser = new pb::MessageParser<a2c_logon_ask>(() => new a2c_logon_ask());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<a2c_logon_ask> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_ask() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_ask(a2c_logon_ask other) : this() {
    publicKey_ = other.publicKey_;
    s_ = other.s_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_ask Clone() {
    return new a2c_logon_ask(this);
  }

  /// <summary>Field number for the "public_key" field.</summary>
  public const int PublicKeyFieldNumber = 1;
  private string publicKey_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string PublicKey {
    get { return publicKey_; }
    set {
      publicKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "s" field.</summary>
  public const int SFieldNumber = 2;
  private string s_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string S {
    get { return s_; }
    set {
      s_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as a2c_logon_ask);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(a2c_logon_ask other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PublicKey != other.PublicKey) return false;
    if (S != other.S) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (PublicKey.Length != 0) hash ^= PublicKey.GetHashCode();
    if (S.Length != 0) hash ^= S.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (PublicKey.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(PublicKey);
    }
    if (S.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(S);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (PublicKey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PublicKey);
    }
    if (S.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(S);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(a2c_logon_ask other) {
    if (other == null) {
      return;
    }
    if (other.PublicKey.Length != 0) {
      PublicKey = other.PublicKey;
    }
    if (other.S.Length != 0) {
      S = other.S;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          PublicKey = input.ReadString();
          break;
        }
        case 18: {
          S = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class c2a_logon_proof : pb::IMessage<c2a_logon_proof> {
  private static readonly pb::MessageParser<c2a_logon_proof> _parser = new pb::MessageParser<c2a_logon_proof>(() => new c2a_logon_proof());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<c2a_logon_proof> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_proof() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_proof(c2a_logon_proof other) : this() {
    a_ = other.a_;
    m1_ = other.m1_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_proof Clone() {
    return new c2a_logon_proof(this);
  }

  /// <summary>Field number for the "A" field.</summary>
  public const int AFieldNumber = 1;
  private string a_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string A {
    get { return a_; }
    set {
      a_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "M1" field.</summary>
  public const int M1FieldNumber = 2;
  private string m1_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string M1 {
    get { return m1_; }
    set {
      m1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as c2a_logon_proof);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(c2a_logon_proof other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (A != other.A) return false;
    if (M1 != other.M1) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (A.Length != 0) hash ^= A.GetHashCode();
    if (M1.Length != 0) hash ^= M1.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (A.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(A);
    }
    if (M1.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(M1);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (A.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(A);
    }
    if (M1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(M1);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(c2a_logon_proof other) {
    if (other == null) {
      return;
    }
    if (other.A.Length != 0) {
      A = other.A;
    }
    if (other.M1.Length != 0) {
      M1 = other.M1;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          A = input.ReadString();
          break;
        }
        case 18: {
          M1 = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class a2c_logon_rep : pb::IMessage<a2c_logon_rep> {
  private static readonly pb::MessageParser<a2c_logon_rep> _parser = new pb::MessageParser<a2c_logon_rep>(() => new a2c_logon_rep());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<a2c_logon_rep> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_rep() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_rep(a2c_logon_rep other) : this() {
    result_ = other.result_;
    username_ = other.username_;
    accountId_ = other.accountId_;
    guid_ = other.guid_;
    sdkCode_ = other.sdkCode_;
    age_ = other.age_;
    isIdentified_ = other.isIdentified_;
    unlockTime_ = other.unlockTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_rep Clone() {
    return new a2c_logon_rep(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::AccountOpResult result_ = 0;
  /// <summary>
  /// 登陆结果(登陆失败不一定能收到)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::AccountOpResult Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 2;
  private string username_ = "";
  /// <summary>
  /// 账号名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "account_id" field.</summary>
  public const int AccountIdFieldNumber = 3;
  private uint accountId_;
  /// <summary>
  /// 账号id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint AccountId {
    get { return accountId_; }
    set {
      accountId_ = value;
    }
  }

  /// <summary>Field number for the "guid" field.</summary>
  public const int GuidFieldNumber = 4;
  private uint guid_;
  /// <summary>
  /// auth guid
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Guid {
    get { return guid_; }
    set {
      guid_ = value;
    }
  }

  /// <summary>Field number for the "sdk_code" field.</summary>
  public const int SdkCodeFieldNumber = 5;
  private int sdkCode_;
  /// <summary>
  /// 平台sdk返回码
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int SdkCode {
    get { return sdkCode_; }
    set {
      sdkCode_ = value;
    }
  }

  /// <summary>Field number for the "age" field.</summary>
  public const int AgeFieldNumber = 6;
  private int age_;
  /// <summary>
  /// 年龄
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Age {
    get { return age_; }
    set {
      age_ = value;
    }
  }

  /// <summary>Field number for the "is_identified" field.</summary>
  public const int IsIdentifiedFieldNumber = 7;
  private bool isIdentified_;
  /// <summary>
  /// 是否实名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool IsIdentified {
    get { return isIdentified_; }
    set {
      isIdentified_ = value;
    }
  }

  /// <summary>Field number for the "unlock_time" field.</summary>
  public const int UnlockTimeFieldNumber = 8;
  private long unlockTime_;
  /// <summary>
  /// 解锁时间(0:永久封号)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long UnlockTime {
    get { return unlockTime_; }
    set {
      unlockTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as a2c_logon_rep);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(a2c_logon_rep other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Result != other.Result) return false;
    if (Username != other.Username) return false;
    if (AccountId != other.AccountId) return false;
    if (Guid != other.Guid) return false;
    if (SdkCode != other.SdkCode) return false;
    if (Age != other.Age) return false;
    if (IsIdentified != other.IsIdentified) return false;
    if (UnlockTime != other.UnlockTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Result != 0) hash ^= Result.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (AccountId != 0) hash ^= AccountId.GetHashCode();
    if (Guid != 0) hash ^= Guid.GetHashCode();
    if (SdkCode != 0) hash ^= SdkCode.GetHashCode();
    if (Age != 0) hash ^= Age.GetHashCode();
    if (IsIdentified != false) hash ^= IsIdentified.GetHashCode();
    if (UnlockTime != 0L) hash ^= UnlockTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Result != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Result);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (AccountId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(AccountId);
    }
    if (Guid != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Guid);
    }
    if (SdkCode != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(SdkCode);
    }
    if (Age != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Age);
    }
    if (IsIdentified != false) {
      output.WriteRawTag(56);
      output.WriteBool(IsIdentified);
    }
    if (UnlockTime != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(UnlockTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Result != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (AccountId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AccountId);
    }
    if (Guid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Guid);
    }
    if (SdkCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SdkCode);
    }
    if (Age != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
    }
    if (IsIdentified != false) {
      size += 1 + 1;
    }
    if (UnlockTime != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(UnlockTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(a2c_logon_rep other) {
    if (other == null) {
      return;
    }
    if (other.Result != 0) {
      Result = other.Result;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.AccountId != 0) {
      AccountId = other.AccountId;
    }
    if (other.Guid != 0) {
      Guid = other.Guid;
    }
    if (other.SdkCode != 0) {
      SdkCode = other.SdkCode;
    }
    if (other.Age != 0) {
      Age = other.Age;
    }
    if (other.IsIdentified != false) {
      IsIdentified = other.IsIdentified;
    }
    if (other.UnlockTime != 0L) {
      UnlockTime = other.UnlockTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          result_ = (global::AccountOpResult) input.ReadEnum();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 24: {
          AccountId = input.ReadUInt32();
          break;
        }
        case 32: {
          Guid = input.ReadUInt32();
          break;
        }
        case 40: {
          SdkCode = input.ReadInt32();
          break;
        }
        case 48: {
          Age = input.ReadInt32();
          break;
        }
        case 56: {
          IsIdentified = input.ReadBool();
          break;
        }
        case 64: {
          UnlockTime = input.ReadInt64();
          break;
        }
      }
    }
  }

}

public sealed partial class a2c_logon_region : pb::IMessage<a2c_logon_region> {
  private static readonly pb::MessageParser<a2c_logon_region> _parser = new pb::MessageParser<a2c_logon_region>(() => new a2c_logon_region());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<a2c_logon_region> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_region() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_region(a2c_logon_region other) : this() {
    ip_ = other.ip_;
    port_ = other.port_;
    httpAddress_ = other.httpAddress_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public a2c_logon_region Clone() {
    return new a2c_logon_region(this);
  }

  /// <summary>Field number for the "ip" field.</summary>
  public const int IpFieldNumber = 1;
  private string ip_ = "";
  /// <summary>
  /// logic ip
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ip {
    get { return ip_; }
    set {
      ip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "port" field.</summary>
  public const int PortFieldNumber = 2;
  private uint port_;
  /// <summary>
  /// logic 端口
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Port {
    get { return port_; }
    set {
      port_ = value;
    }
  }

  /// <summary>Field number for the "http_address" field.</summary>
  public const int HttpAddressFieldNumber = 3;
  private string httpAddress_ = "";
  /// <summary>
  /// logic_http 地址ip:port
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string HttpAddress {
    get { return httpAddress_; }
    set {
      httpAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as a2c_logon_region);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(a2c_logon_region other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Ip != other.Ip) return false;
    if (Port != other.Port) return false;
    if (HttpAddress != other.HttpAddress) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Ip.Length != 0) hash ^= Ip.GetHashCode();
    if (Port != 0) hash ^= Port.GetHashCode();
    if (HttpAddress.Length != 0) hash ^= HttpAddress.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Ip.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Ip);
    }
    if (Port != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Port);
    }
    if (HttpAddress.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(HttpAddress);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Ip.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ip);
    }
    if (Port != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
    }
    if (HttpAddress.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HttpAddress);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(a2c_logon_region other) {
    if (other == null) {
      return;
    }
    if (other.Ip.Length != 0) {
      Ip = other.Ip;
    }
    if (other.Port != 0) {
      Port = other.Port;
    }
    if (other.HttpAddress.Length != 0) {
      HttpAddress = other.HttpAddress;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Ip = input.ReadString();
          break;
        }
        case 16: {
          Port = input.ReadUInt32();
          break;
        }
        case 26: {
          HttpAddress = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class c2a_logon_sdk : pb::IMessage<c2a_logon_sdk> {
  private static readonly pb::MessageParser<c2a_logon_sdk> _parser = new pb::MessageParser<c2a_logon_sdk>(() => new c2a_logon_sdk());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<c2a_logon_sdk> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_sdk() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_sdk(c2a_logon_sdk other) : this() {
    openId_ = other.openId_;
    appId_ = other.appId_;
    cchId_ = other.cchId_;
    accessToken_ = other.accessToken_;
    appKey_ = other.appKey_;
    sdkType_ = other.sdkType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_sdk Clone() {
    return new c2a_logon_sdk(this);
  }

  /// <summary>Field number for the "open_id" field.</summary>
  public const int OpenIdFieldNumber = 1;
  private string openId_ = "";
  /// <summary>
  /// 账号名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string OpenId {
    get { return openId_; }
    set {
      openId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "app_id" field.</summary>
  public const int AppIdFieldNumber = 2;
  private string appId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AppId {
    get { return appId_; }
    set {
      appId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "cch_id" field.</summary>
  public const int CchIdFieldNumber = 3;
  private string cchId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string CchId {
    get { return cchId_; }
    set {
      cchId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "access_token" field.</summary>
  public const int AccessTokenFieldNumber = 4;
  private string accessToken_ = "";
  /// <summary>
  /// 登陆令牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AccessToken {
    get { return accessToken_; }
    set {
      accessToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "app_key" field.</summary>
  public const int AppKeyFieldNumber = 5;
  private string appKey_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AppKey {
    get { return appKey_; }
    set {
      appKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sdk_type" field.</summary>
  public const int SdkTypeFieldNumber = 6;
  private string sdkType_ = "";
  /// <summary>
  /// login_url中sdk key
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string SdkType {
    get { return sdkType_; }
    set {
      sdkType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as c2a_logon_sdk);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(c2a_logon_sdk other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (OpenId != other.OpenId) return false;
    if (AppId != other.AppId) return false;
    if (CchId != other.CchId) return false;
    if (AccessToken != other.AccessToken) return false;
    if (AppKey != other.AppKey) return false;
    if (SdkType != other.SdkType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (OpenId.Length != 0) hash ^= OpenId.GetHashCode();
    if (AppId.Length != 0) hash ^= AppId.GetHashCode();
    if (CchId.Length != 0) hash ^= CchId.GetHashCode();
    if (AccessToken.Length != 0) hash ^= AccessToken.GetHashCode();
    if (AppKey.Length != 0) hash ^= AppKey.GetHashCode();
    if (SdkType.Length != 0) hash ^= SdkType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (OpenId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(OpenId);
    }
    if (AppId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AppId);
    }
    if (CchId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(CchId);
    }
    if (AccessToken.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(AccessToken);
    }
    if (AppKey.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(AppKey);
    }
    if (SdkType.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(SdkType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (OpenId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OpenId);
    }
    if (AppId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppId);
    }
    if (CchId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CchId);
    }
    if (AccessToken.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessToken);
    }
    if (AppKey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppKey);
    }
    if (SdkType.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SdkType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(c2a_logon_sdk other) {
    if (other == null) {
      return;
    }
    if (other.OpenId.Length != 0) {
      OpenId = other.OpenId;
    }
    if (other.AppId.Length != 0) {
      AppId = other.AppId;
    }
    if (other.CchId.Length != 0) {
      CchId = other.CchId;
    }
    if (other.AccessToken.Length != 0) {
      AccessToken = other.AccessToken;
    }
    if (other.AppKey.Length != 0) {
      AppKey = other.AppKey;
    }
    if (other.SdkType.Length != 0) {
      SdkType = other.SdkType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          OpenId = input.ReadString();
          break;
        }
        case 18: {
          AppId = input.ReadString();
          break;
        }
        case 26: {
          CchId = input.ReadString();
          break;
        }
        case 34: {
          AccessToken = input.ReadString();
          break;
        }
        case 42: {
          AppKey = input.ReadString();
          break;
        }
        case 50: {
          SdkType = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class c2a_logon_apple : pb::IMessage<c2a_logon_apple> {
  private static readonly pb::MessageParser<c2a_logon_apple> _parser = new pb::MessageParser<c2a_logon_apple>(() => new c2a_logon_apple());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<c2a_logon_apple> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[8]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_apple() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_apple(c2a_logon_apple other) : this() {
    userIdentifier_ = other.userIdentifier_;
    identityToken_ = other.identityToken_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_apple Clone() {
    return new c2a_logon_apple(this);
  }

  /// <summary>Field number for the "user_identifier" field.</summary>
  public const int UserIdentifierFieldNumber = 1;
  private string userIdentifier_ = "";
  /// <summary>
  /// 账号名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserIdentifier {
    get { return userIdentifier_; }
    set {
      userIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "identity_token" field.</summary>
  public const int IdentityTokenFieldNumber = 2;
  private string identityToken_ = "";
  /// <summary>
  /// JSON Web Token (JWT) 只有第一次登录注册有用,以后都只看账号名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IdentityToken {
    get { return identityToken_; }
    set {
      identityToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as c2a_logon_apple);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(c2a_logon_apple other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserIdentifier != other.UserIdentifier) return false;
    if (IdentityToken != other.IdentityToken) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (UserIdentifier.Length != 0) hash ^= UserIdentifier.GetHashCode();
    if (IdentityToken.Length != 0) hash ^= IdentityToken.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (UserIdentifier.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserIdentifier);
    }
    if (IdentityToken.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(IdentityToken);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (UserIdentifier.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserIdentifier);
    }
    if (IdentityToken.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdentityToken);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(c2a_logon_apple other) {
    if (other == null) {
      return;
    }
    if (other.UserIdentifier.Length != 0) {
      UserIdentifier = other.UserIdentifier;
    }
    if (other.IdentityToken.Length != 0) {
      IdentityToken = other.IdentityToken;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserIdentifier = input.ReadString();
          break;
        }
        case 18: {
          IdentityToken = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class c2a_logon_google : pb::IMessage<c2a_logon_google> {
  private static readonly pb::MessageParser<c2a_logon_google> _parser = new pb::MessageParser<c2a_logon_google>(() => new c2a_logon_google());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<c2a_logon_google> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[9]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_google() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_google(c2a_logon_google other) : this() {
    googleId_ = other.googleId_;
    idToken_ = other.idToken_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_google Clone() {
    return new c2a_logon_google(this);
  }

  /// <summary>Field number for the "google_id" field.</summary>
  public const int GoogleIdFieldNumber = 1;
  private string googleId_ = "";
  /// <summary>
  /// Google ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string GoogleId {
    get { return googleId_; }
    set {
      googleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "id_token" field.</summary>
  public const int IdTokenFieldNumber = 2;
  private string idToken_ = "";
  /// <summary>
  /// id_token
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IdToken {
    get { return idToken_; }
    set {
      idToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as c2a_logon_google);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(c2a_logon_google other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (GoogleId != other.GoogleId) return false;
    if (IdToken != other.IdToken) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (GoogleId.Length != 0) hash ^= GoogleId.GetHashCode();
    if (IdToken.Length != 0) hash ^= IdToken.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (GoogleId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(GoogleId);
    }
    if (IdToken.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(IdToken);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (GoogleId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GoogleId);
    }
    if (IdToken.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdToken);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(c2a_logon_google other) {
    if (other == null) {
      return;
    }
    if (other.GoogleId.Length != 0) {
      GoogleId = other.GoogleId;
    }
    if (other.IdToken.Length != 0) {
      IdToken = other.IdToken;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          GoogleId = input.ReadString();
          break;
        }
        case 18: {
          IdToken = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class c2a_logon_super : pb::IMessage<c2a_logon_super> {
  private static readonly pb::MessageParser<c2a_logon_super> _parser = new pb::MessageParser<c2a_logon_super>(() => new c2a_logon_super());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<c2a_logon_super> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[10]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_super() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_super(c2a_logon_super other) : this() {
    username_ = other.username_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_super Clone() {
    return new c2a_logon_super(this);
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 2;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as c2a_logon_super);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(c2a_logon_super other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Username != other.Username) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(c2a_logon_super other) {
    if (other == null) {
      return;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 18: {
          Username = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class c2a_logon_apple_gamecenter : pb::IMessage<c2a_logon_apple_gamecenter> {
  private static readonly pb::MessageParser<c2a_logon_apple_gamecenter> _parser = new pb::MessageParser<c2a_logon_apple_gamecenter>(() => new c2a_logon_apple_gamecenter());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<c2a_logon_apple_gamecenter> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[11]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_apple_gamecenter() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_apple_gamecenter(c2a_logon_apple_gamecenter other) : this() {
    userIdentifier_ = other.userIdentifier_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public c2a_logon_apple_gamecenter Clone() {
    return new c2a_logon_apple_gamecenter(this);
  }

  /// <summary>Field number for the "user_identifier" field.</summary>
  public const int UserIdentifierFieldNumber = 1;
  private string userIdentifier_ = "";
  /// <summary>
  /// 账号名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserIdentifier {
    get { return userIdentifier_; }
    set {
      userIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as c2a_logon_apple_gamecenter);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(c2a_logon_apple_gamecenter other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserIdentifier != other.UserIdentifier) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (UserIdentifier.Length != 0) hash ^= UserIdentifier.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (UserIdentifier.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserIdentifier);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (UserIdentifier.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserIdentifier);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(c2a_logon_apple_gamecenter other) {
    if (other == null) {
      return;
    }
    if (other.UserIdentifier.Length != 0) {
      UserIdentifier = other.UserIdentifier;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserIdentifier = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
